//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQRS.Demo.Infrastructure.EventStore.SqlServer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoggedEvents
    {
        public int Id { get; set; }
        public string Action { get; set; }
        public int AggregateId { get; set; }
        public string Cargo { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
